pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral(); maven { url = uri('vendor/openvpn-engine/android/localmaven') } } }
rootProject.name = 'SNAPTVNOW'
include ':app'
